// Generated by CoffeeScript 1.10.0
(function() {
  var Nano, counter, int, nano, util;

  Nano = require('nano');

  util = require('util');

  nano = new Nano({
    url: 'http://cliff:ph10na@pro1:5984'
  });

  counter = 0;

  int = setInterval(function() {
    process.stdout.write('.');
    if (++counter % 60 === 0) {
      return process.stdout.write("\n");
    }
  }, 1000);

  nano.db.changes('alice', function(err, result) {
    var seq;
    seq = result.last_seq;
    return nano.db.changes('alice', {
      feed: 'longpoll',
      since: seq,
      heartbeat: true
    }, function(err, result) {
      clearInterval(int);
      process.stdout.write("\n");
      return console.log(util.inspect((err ? err.toString() : result), {
        depth: null,
        colors: true
      }));
    });
  });

}).call(this);
